name: Exemplo
on: 
    push:
        branches: 
            - main

jobs:
    
    teste:
        runs-on: ubuntu-latest
        steps:
            - name: Liberando o acesso
              uses: actions/checkout@v4

            - name: Instalando o NODE
              uses: actions/setup-node@v4
            
            - name: Testando o código
              run: npm install 
            - run: npm test


    deploy:
        needs: teste
        runs-on: ubuntu-latest
        permissions: 
            contents: write
        steps:
            - name: Liberando acesso aos dados
              uses: actions/checkout@v4
            
            - name: Executando o Merge na Github Pages
              run: git config user.email "carloswgama@gmail.com" 
            - run: git config user.name "Carlos W. Gama"
            - run: git fetch
            - run: git checkout -B gh-pages
            - run: git merge main
            - run: git push --force origin gh-pages