name: Exemplo
on: 
    push:
        branches: 
            - main

jobs:
    
    teste:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Testando 123"

    exemplo2:
        needs: teste
        runs-on: ubuntu-latest
        steps:
            - run: echo "Testando segunda job"