name: Exemplo
on: 
    push:
        branches: 
            - main

jobs:
    
    teste:
        runs-on: ubuntu-latest
        steps:
            - name: Liberando o acesso
              uses: actions/checkout
              
            - name: Instalando o NODE
              uses: actions/setup-node@v4
            
            - name: Testando o código
              run: npm install 
            - run: npm test


    deploy:
        needs: teste
        runs-on: ubuntu-latest
        steps:
            - run: echo "Testando segunda job"